### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by TMarafon** [CharlieDigital/coderev#4]
Ideas:
1. Very often in my code reviews, it is useful to leave a comment suggesting a different code. It would be nice if the code reviewer had an easy way to format code on CodeRev.
2. Threads in comments are also very common and useful. 
3. CodeRev allows the candidate to review code as if they were reviewing a repo. One idea to really simulate a PR review would be to provide two versions of a code, highlighting the difference. So the candidate would be able to evaluate if the changes are making the code better/worse, if the names of variables, functions, etc still make sense, and other situations.

**Comment by CharlieDigital** [comment]
Great ideas; I think (2) is the easiest and (1) I need to give some thought. 

Right now, the storage scheme is quite efficient since it doesn't require supporting editing (which would require storing either a diff or the full, edited file).  Need to think about an efficient way to store those edits.

**Comment by CharlieDigital** [comment]
Added the option to add simple, 1-level threaded comment replies: 

![image](https://github.com/CharlieDigital/coderev/assets/779970/9b2a9d4c-5760-451c-9ff9-19b005f1f48c)
